### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by theamazing0** [tom-james-watson/detoxed.news#16]
Light text on dark background, triggered by browser dark setting. Would also be optimal to have some button to toggle by the user.

**Comment by theamazing0** [comment]
@tom-james-watson Can I work on adding this?

**Comment by tom-james-watson** [comment]
Yeah, sure! Though this should just be automatic based on the user's browser settings - I don't want to have a new toggle in the UI.

**Comment by theamazing0** [comment]
Do you think something like detoxed.news/dark would make sense for users of Tor and other anti fingerprinting browsers? Or would that just be unnecessary?

**Comment by tom-james-watson** [comment]
What do you mean by "detoxed.news/dark"?

**Comment by theamazing0** [comment]
Some anti fingerprinting browsers like Tor have the browser report light mode by default, and users aren't supposed to usually change it because it will make their fingerprint more unique.

Currently, "detoxed.news" is going to display dark/light based on the browser setting, but on browsers like Tor this will always be dark. Maybe at "detoxed.news/dark" it could always display dark?

**Comment by tom-james-watson** [comment]
Ahhh ok. No - I'm not interested in supporting that - unnecessary IMO.
